name: geeklibrary
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^1.0.1
  cached_network_image: ^3.0.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.3
  device_preview: ^0.7.4
  dio: ^4.0.0
  encrypt: ^5.0.0
  eva_icons_flutter: ^3.0.0
  firebase: ^9.0.1
  firebase_core: ^1.4.0
  flash: ^2.0.1
  flutter_inappwebview: ^5.3.2
  flutter_phoenix: ^1.0.0
  flutter_riverpod: ^0.14.0+3
  flutter_screenutil: ^5.0.0+2
  flutter_secure_storage: ^4.2.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.1.0
  get: ^4.1.4
  google_fonts: ^2.1.0
  google_mobile_ads: ^0.13.2
  google_sign_in: ^5.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  intl: ^0.17.0
  ionicons: ^0.1.2
  line_icons: ^2.0.1
  logger: ^1.0.0
  lottie: ^1.0.1
  numberpicker: ^2.1.1
  palette_generator: ^0.3.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.2
  photo_view: ^0.11.1
  pointycastle: ^3.1.3
  readmore: ^2.1.0
  shimmer: ^2.0.0
  sign_button: ^2.0.0
  string_validator: ^0.3.0
  translator: ^0.1.7
  typicons_flutter: ^0.5.0
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^1.1.0

# dependency_overrides:
#   pointycastle: ^3.2.0-rc0
flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/shapes/
    - assets/images/vectors/
    - assets/images/avatar/
    - assets/images/avatars/

  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro/MavenPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/MavenPro/MavenPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/MavenPro/MavenPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MavenPro/MavenPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/MavenPro/MavenPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MavenPro/MavenPro-Black.ttf
          weight: 900

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Mulish/Mulish-Light.ttf
          weight: 300

        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
          weight: 400

        - asset: assets/fonts/Mulish/Mulish-Medium.ttf
          weight: 500

        - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
          weight: 700

        - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Mulish/Mulish-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100

        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300

        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300

        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400

        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700

        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900

    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Light.ttf
          weight: 300

        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Regular.ttf
          weight: 400

        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Bold.ttf
          weight: 700

        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Black.ttf
          weight: 900
