name: geeklibrary
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^1.0.1
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  encrypt: ^5.0.0
  eva_icons_flutter: ^3.0.0
  firebase: ^9.0.1
  firebase_app_check: ^0.0.2+1
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  flutter_local_notifications: ^8.1.1+2
  flutter_phoenix: ^1.0.0
  flutter_riverpod: ^0.14.0+3
  flutter_screenutil: ^5.0.0+2
  flutter_secure_storage: ^4.2.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  flutter_windowmanager: ^0.2.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.1.0
  get: ^4.1.4
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  intl: ^0.17.0
  ionicons: ^0.1.2
  line_icons: ^2.0.1
  logger: ^1.0.0
  lottie: ^1.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.2
  permission_handler: ^8.1.2
  photo_view: ^0.11.1
  pointycastle: ^3.1.3
  readmore: ^2.1.0
  shimmer: ^2.0.0
  string_validator: ^0.3.0
  translator: ^0.1.7
  typicons_flutter: ^0.5.0
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

# dependency_overrides:
#   pointycastle: ^3.2.0-rc0
flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/png/
    - assets/images/shapes/
